### PR TITLE
Clear up travis

### PR DESCRIPTION
**Pull request by bsipocz**
Changes on L120&123 should do the trick unless I messed up something with the rest.

### CODE REVIEW

**Comment by bmorris3** [comment]
@bsipocz It looks like travis wasn't triggered by this PR?

**Comment by bsipocz** [comment]
Weird. Do you have it turned on your fork for PRs?

**Comment by bmorris3** [comment]
Yes, I believe so. Appveyor is still working.

**Comment by bsipocz** [comment]
Re travis build time, I think it can still cut back a bit more:
- I think it's reasonable to build only one sphinx build. If you want to be progressive, keep the 3.5
- using astropy's approach older pythons, 3.3 and 3.4 under the same amount of time if mixed and matched with the old numpy versions.
- probably can cut back the non remote tests, too.

Let me know if you want to go down this path and want me to open a PR for it.

**Pull request merged**
